# Generated by Django 5.0.3 on 2026-07-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(db_column='Admin_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(db_column='Appointment_ID', primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(blank=True, db_column='Appointment_Date', null=True)),
                ('appointment_time', models.TimeField(blank=True, db_column='Appointment_Time', null=True)),
                ('reason', models.TextField(blank=True, db_column='Reason', null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='Status', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='Department_ID', primary_key=True, serialize=False)),
                ('department_name', models.CharField(db_column='Department_Name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(db_column='Doctor_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('qualification', models.CharField(blank=True, db_column='Qualification', max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, db_column='Specialization', max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, db_column='Experience', null=True)),
                ('hospital', models.CharField(blank=True, db_column='Hospital', max_length=100, null=True)),
                ('fees', models.DecimalField(blank=True, db_column='Fees', decimal_places=2, max_digits=10, null=True)),
                ('available_days', models.CharField(blank=True, db_column='Available_Days', max_length=100, null=True)),
                ('available_time', models.CharField(blank=True, db_column='Available_Time', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(db_column='Patient_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_column='Gender', max_length=10, null=True)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(db_column='Prescription_ID', primary_key=True, serialize=False)),
                ('diagnosis', models.TextField(blank=True, db_column='Diagnosis', null=True)),
                ('medicine', models.CharField(blank=True, db_column='Medicine', max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, db_column='Dosage', max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, db_column='Instructions', null=True)),
            ],
            options={
                'db_table': 'Prescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(db_column='Notification_ID', primary_key=True, serialize=False)),
                ('user_type', models.CharField(db_column='User_Type', max_length=20)),
                ('user_id', models.IntegerField(db_column='User_ID')),
                ('message', models.TextField(db_column='Message')),
                ('is_read', models.BooleanField(db_column='Is_Read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(db_column='Review_ID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('doctor', models.ForeignKey(db_column='Doctor_ID', on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
    ]
